Update google.golang.org/grpc to fix the build
Starting with db6fec71fa8bdfdb44007b61f355b4e5d8e2a564 mirrorbits fails to build with:

rpc/rpc.pb.go:1411:12: undefined: grpc.ClientConnInterface
rpc/rpc.pb.go:1415:16: undefined: grpc.SupportPackageIsVersion6
rpc/rpc.pb.go:1442:10: undefined: grpc.ClientConnInterface
rpc/rpc.pb.go:1445:27: undefined: grpc.ClientConnInterface

This is due to the generated rpc/rpc.pb.go depending on a newer version
of google.golang.org/grpc.

This bumps the version to the next minor version that fixes the build,
to keep the diff small.

Fixes #172